### ISSUE TITLE
HTTP 502 after deploying app launcher

### ISSUE THREAD

**Issue by videlanicolas** [GoogleCloudPlatform/selkies#2]
Followed the [setup steps](https://github.com/GoogleCloudPlatform/selkies/blob/master/setup/README.md) on region `australia-southeast1`. All steps completed successfully but when accessing the app broker's webpage (https://broker.endpoints.{$PROJECT_ID}.cloud.goog/) it returns HTTP 502 with the following message:

```
Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.
```

The cluster is up and running normally (i.e. the cluster is not reporting errors and deployed all nodes correctly), I went to Cloud Logging for some clues and I'm seeing recurring errors like the following:

```
{
  "textPayload": "2020/07/12 13:32:29 http: TLS handshake error from x.x.x.20:38700: remote error: tls: bad certificate\n",
  "insertId": "l9x0...zk1i",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "container_name": "kube-rbac-proxy",
      "location": "australia-southeast1",
      "namespace_name": "autoneg-system",
      "cluster_name": "broker-australia-southeast1",
      "project_id": "{$PROJECT_ID}",
      "pod_name": "autoneg-controller-manager-54...cc-n...z"
    }
  },
  "timestamp": "2020-07-12T13:32:29.849992671Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/pod-template-hash": "54...cc",
    "k8s-pod/control-plane": "controller-manager"
  },
  "logName": "projects/{$PROJECT_ID}/logs/stderr",
  "receiveTimestamp": "2020-07-12T13:32:34.856591234Z"
}
```

I downgraded the cluster's Kubernetes version from `1.16.9-gke.6` (Release channel) to `1.14.10-gke.36` (Stable channel) in hope of fixing this but the error is still there. I tried deploying this on `us-west1` but I'm getting the same results.

```bash
$ gcloud container clusters list
NAME                         LOCATION              MASTER_VERSION  MASTER_IP      MACHINE_TYPE   NODE_VERSION    NUM_NODES  STATUS
broker-australia-southeast1  australia-southeast1  1.14.10-gke.36  x.x.x.x  n1-standard-4  1.14.10-gke.36  3          RUNNING
```
```bash
$ gcloud container node-pools list --region australia-southeast1 --cluster=broker-australia-southeast1
NAME               MACHINE_TYPE   DISK_SIZE_GB  NODE_VERSION
default-node-pool  n1-standard-4  200           1.14.10-gke.36
turn               n1-standard-2  200           1.14.10-gke.36
tier2              n1-highcpu-32  200           1.14.10-gke.36
tier1              n1-standard-4  200           1.14.10-gke.36
gpu-cos            n1-standard-8  200           1.14.10-gke.36
```

Is there some other information I can provide? Could this be a problem on Terraform/Kubernetes instead?

**Comment by videlanicolas** [comment]
I think this is because the load balancer has a backend service (`istio-ingressgateway`) with no instance groups or network endpoint groups. I added `k8s1-685dead7-istio-system-istio-ingressgateway-80-9ca2df6e` network endpoint group as a backend to `istio-ingressgateway`, now I get a working landing page with no apps. I guess there's a missing step that's not adding the backend network endpoint group to the backend ingress gateway?

**Comment by danisla** [comment]
Sometimes the Autoneg controller flakes out and the NEGs aren't registered with the backend service.

Run the [`./setup/scripts/fix_autoneg.sh`](https://github.com/GoogleCloudPlatform/selkies/blob/dev/setup/scripts/fix_autoneg.sh) script to fix it, same commands in the script are below:

```bash
kubectl annotate service istio-ingressgateway -n istio-system cloud.google.com/neg-status-
kubectl annotate service istio-ingressgateway -n istio-system anthos.cft.dev/autoneg-status-
```

**Comment by videlanicolas** [comment]
I started a new project from scratch and used those two commands at the end, it fixed everything for me now. Thanks!
